[build]
  base = "HealLinkConnect"
  command = "npm run build"
  publish = "HealLinkConnect/dist/public"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_BACKEND_URL/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
