[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  # Set Vite env var for the frontend to call the backend API
  # Add VITE_API_URL in Netlify site settings to point to your backend, e.g. https://api.yourdomain.com
  # VITE_API_URL = "https://your-backend.example.com"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend.example.com/:splat"
  status = 200
  force = true
