name: CI & Netlify Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HealLinkConnect
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist/public

  netlify_deploy:
    name: Deploy to Netlify (if secrets present)
    needs: build
    runs-on: ubuntu-latest
    # Only run deploy step when Netlify secrets are configured
    if: ${{ secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install netlify CLI
        run: npm ci --workspace=.

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify --version
          npx netlify deploy --dir=HealLinkConnect/dist/public --prod --site=$NETLIFY_SITE_ID
